
export const keywords: string[] = [
  'web development',
  'software development',
  'web technologies',
  'coding skills',
  'tools and technologies',
  'latest trends',
  'JavaScript',
  'React',
  'Node.js',
  'TypeScript',
  'CSS',
  'HTML',
  'web design',
  'web development tools',
  'web development technologies',
  'web development trends',
  'web development tips',
  'web development tutorials',
  'web development resources',
  'web development courses',
  'web development blogs',
  'web development news',
  'web development articles',
  'web development books',
  'web development podcasts',
  'web development videos',
  'web development conferences',
  'web development events',
  'web development jobs',
  'web development internships',
  'web development remote jobs',
  'web development freelance jobs',
  'web development full-time jobs',
  'web development part-time jobs',
  'web development contract jobs',
  'web development consulting jobs',
  'web development training',
  'web development certifications',
  'web development bootcamps',
  'web development workshops',
  'web development meetups',
  'web development communities',
  'web development forums',
  'web development social media',
  'web development newsletters',
  'web development podcasts',
  'web development videos',
  'web development conferences',
  'web development events',
  'web development jobs',
  'web development internships',
  'web development remote jobs',
  'web development freelance jobs',
  'web development full-time jobs',
  'web development part-time jobs',
  'web development contract jobs',
  'web development consulting jobs',
  'web development training',
  'web development certifications',
  'web development bootcamps',
  'web development workshops',
  'web development meetups',
  'web development communities',
  'web development forums',
  'web development social media',
  'web development newsletters',
  'web development podcasts',
  'web development videos',
  'web development conferences',
  'web development events',
  'web development jobs',
  'web development internships',
  'web development remote jobs',
  'web development freelance jobs',
  'web development full-time jobs',
  'web development part-time jobs',
  'web development contract jobs',
  'web development consulting jobs',
  'web development training',
  'web development certifications',
  'web development bootcamps',
  'web development workshops',
  'web development meetups',
  'web development communities',
  'web development forums',
  'web development social media',
  'web development newsletters',
  'web development podcasts',
  'web development videos',
  'web development conferences',
  'web development events',
  'web development jobs',
  'web development internships',
  'web development remote jobs',
  'web development freelance jobs',
  'web development full-time jobs',
  'web development part-time jobs',
  'web development contract jobs',
  'web development consulting jobs',
  'web development training',
  'web development certifications',
  'web development bootcamps',
  'web development workshops',
  'web development meetups',
  'web development communities',
  'web development forums',
]